import { CodeBlock, Note, Tip } from '@/components/ui'

export function SessionsCookies() {
  return (
    <div className="space-y-6">
      <section>
        <h2 id="sessions-cookies" className="text-[#FF2D20] mt-10 text-2xl font-semibold">
          Sessions & Cookies
        </h2>
        <p>Since HTTP driven applications are stateless, sessions provide a way to store information about the user across multiple requests. Laravel ships with a variety of session backends that are accessed through an expressive, unified API.</p>
        
        <h3 className="text-[#5f6368] mt-6 font-semibold">Interacting With the Session</h3>
        <CodeBlock>{`// Retrieve data
$value = session('key');
$value = $request->session()->get('key', 'default');

// Store data
session(['key' => 'value']);
$request->session()->put('key', 'value');

// Flash data (Only available for the next request)
$request->session()->flash('status', 'Task was successful!');`}</CodeBlock>

        <Tip>
          <strong>JS Tip:</strong> Laravel sessions are managed server-side. Unlike JavaScript apps that often store everything in <code className="bg-[#f5f5f5] px-1.5 py-0.5 rounded font-mono text-sm">localStorage</code>, Laravel uses a secure session ID cookie to link the browser to server-side data (Database, Redis, or Files).
        </Tip>
      </section>

      <section>
        <h3 id="cookies" className="text-[#5f6368] mt-8 font-semibold">Cookies</h3>
        <p>Laravel uses the <code className="bg-[#f5f5f5] px-1.5 py-0.5 rounded font-mono text-sm">Cookie</code> facade or the <code className="bg-[#f5f5f5] px-1.5 py-0.5 rounded font-mono text-sm">cookie()</code> helper to manage cookies. All cookies generated by Laravel are encrypted and signed with an authentication code, meaning they will be considered invalid if they have been client-side modified.</p>
        <CodeBlock>{`// Attaching a cookie to a response
return response('Hello World')->cookie(
    'name', 'value', $minutes
);

// Retrieving a cookie
$value = $request->cookie('name');`}</CodeBlock>
      </section>

      <hr className="border-none border-t border-[#ddd] my-10" />
    </div>
  )
}
